# Generated by Django 2.1.7 on 2019-04-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190218_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
