# Generated by Django 2.1.7 on 2019-04-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_temps',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
