# Generated by Django 2.1.7 on 2019-04-21 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_temps',
            new_name='date_de_debut',
        ),
        migrations.AddField(
            model_name='post',
            name='date_de_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
