# Generated by Django 2.1.7 on 2019-04-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190421_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_de_debut',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_de_fin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url_test',
        ),
    ]
