# Generated by Django 2.1.7 on 2019-04-24 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190423_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_de_debut',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='date_de_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='{%static img/fond1.jpg %}', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='url_test',
            field=models.URLField(default='www.pierre-dauphin.hopto.org'),
        ),
    ]
